<?xml version="1.0" encoding="utf-8"?>
<EntityImageConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <parententitylogicalname>soap_product</parententitylogicalname>
  <primaryimageattribute>soap_productimage</primaryimageattribute>
</EntityImageConfig>