<?xml version="1.0" encoding="utf-8"?>
<AttributeImageConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <attributelogicalname>soap_productimage</attributelogicalname>
  <parententitylogicalname>soap_product</parententitylogicalname>
  <canstorefullimage>1</canstorefullimage>
</AttributeImageConfig>